/* 锐枫皮业目录数据。图与价供展会对照，不是实时库存。
   系列按设计师常问的粒面写：Togo / Swift / Epsom / 掌纹 / 摔纹 / 小纹 / 盒纹 / 大纹。
   前台不要写对标品牌。Togo、Swift、Epsom 是粒面检索名。
   色号 RF-xxxx 固定，不复用。屏幕色仅供参考，以实物和色号为准。 */
window.RUIFENG = {
  wechat: "ruifeng-demo",
  email: "hello@ruifengleather.com",
  categories: [
    {
      id: "togo",
      zh: "Togo纹",
      en: "Togo",
      line_zh: "大卵石粒，挺，耐刮，适合包",
      line_en: "Large pebble, firm, scratch-tough — bags",
      photo: "img/grains/togo.jpg",
      photo_fallback: "img/atelier/grain-calf.jpg",
      swatch: "oxblood",
      coreColors: ["black", "gold", "etoupe", "cognac", "craie", "navy"]
    },
    {
      id: "swift",
      zh: "Swift纹",
      en: "Swift",
      line_zh: "极细软面，适合小皮件",
      line_en: "Very fine soft face — small leather",
      photo: "img/grains/swift.jpg",
      photo_fallback: "img/atelier/box-calf.jpg",
      swatch: "honey",
      coreColors: ["black", "gold", "etoupe", "cognac", "craie", "navy"]
    },
    {
      id: "epsom",
      zh: "Epsom纹",
      en: "Epsom",
      line_zh: "规则压纹，硬挺好打理",
      line_en: "Regular press grain, firm, easy care",
      photo: "img/grains/epsom.jpg",
      photo_fallback: "img/atelier/grain-calf.jpg",
      swatch: "black",
      coreColors: ["black", "gold", "etoupe", "cognac", "craie", "navy"]
    },
    {
      id: "clemence",
      zh: "掌纹",
      en: "Palm grain",
      line_zh: "大掌纹，松软",
      line_en: "Large palm grain, slack and soft",
      photo: "img/grains/clemence.jpg",
      photo_fallback: "img/atelier/grain-calf.jpg",
      swatch: "chestnut",
      coreColors: ["black", "gold", "etoupe", "cognac", "craie", "navy"]
    },
    {
      id: "tumbled",
      zh: "摔纹",
      en: "Tumbled",
      line_zh: "自然摔皱",
      line_en: "Natural tumbled creases",
      photo: "img/grains/tumbled.jpg",
      photo_fallback: "img/atelier/veg-calf.jpg",
      swatch: "olive",
      coreColors: ["black", "gold", "etoupe", "cognac", "olive", "navy"]
    },
    {
      id: "lychee",
      zh: "小纹",
      en: "Fine pebble",
      line_zh: "细荔枝小纹",
      line_en: "Fine lychee pebble",
      photo: "img/grains/lychee-small.jpg",
      photo_fallback: "img/atelier/grain-calf.jpg",
      swatch: "camel",
      coreColors: ["black", "gold", "etoupe", "cognac", "craie", "navy"]
    },
    {
      id: "box",
      zh: "光面盒纹",
      en: "Box calf",
      line_zh: "光面挺括",
      line_en: "Smooth and firm",
      photo: "img/atelier/box-calf.jpg",
      photo_fallback: "img/atelier/box-calf.jpg",
      swatch: "black",
      coreColors: ["black", "gold", "etoupe", "cognac", "craie", "navy"]
    },
    {
      id: "lychee-large",
      zh: "大纹",
      en: "Large pebble",
      line_zh: "大荔枝纹（图暂用小纹特写对照）",
      line_en: "Large lychee pebble (fine-pebble photo for now)",
      photo: "img/grains/lychee-small.jpg",
      photo_fallback: "img/atelier/grain-calf.jpg",
      photo_is_fallback: true,
      photo_note_zh: "暂无独立大纹特写，图用小纹对照。9月1日展会看实样。",
      photo_note_en: "No unique large-pebble photo yet — fine pebble shown. See the hide at the 1 Sept fair.",
      swatch: "wine",
      coreColors: ["black", "gold", "etoupe", "cognac", "wine", "navy"]
    }
  ],
  colorFamilies: [
    { id: "dark",       zh: "深色", en: "Dark" },
    { id: "grey",       zh: "灰色", en: "Grey" },
    { id: "gold-brown", zh: "金棕", en: "Gold-brown" },
    { id: "red",        zh: "红色", en: "Red" },
    { id: "orange",     zh: "橙色", en: "Orange" },
    { id: "yellow",     zh: "黄色", en: "Yellow" },
    { id: "green",      zh: "绿色", en: "Green" },
    { id: "blue",       zh: "蓝色", en: "Blue" },
    { id: "pink",       zh: "粉色", en: "Pink" },
    { id: "purple",     zh: "紫色", en: "Purple" },
    { id: "light",      zh: "浅色", en: "Light" }
  ],
  colors: {
    "black":        { zh: "墨黑",     en: "Noir",         hex: "#1a1816", family: "dark",       code: "RF-1001" },
    "graphite":     { zh: "石墨",     en: "Graphite",     hex: "#2a2a28", family: "dark",       code: "RF-1002" },
    "charcoal":     { zh: "炭灰",     en: "Charcoal",     hex: "#2e2c2a", family: "dark",       code: "RF-1003" },
    "deep-brown":   { zh: "深棕",     en: "Deep brown",   hex: "#3c2418", family: "dark",       code: "RF-1004" },
    "etain":        { zh: "锡灰",     en: "Etain",        hex: "#6e6860", family: "grey",       code: "RF-2001" },
    "beton":        { zh: "水泥灰",   en: "Beton",        hex: "#8a847c", family: "grey",       code: "RF-2002" },
    "gris":         { zh: "中灰",     en: "Gris",         hex: "#7a746c", family: "grey",       code: "RF-2003" },
    "ash":          { zh: "烟灰",     en: "Ash",          hex: "#9e9890", family: "grey",       code: "RF-2004" },
    "gris-perle":   { zh: "珍珠灰",   en: "Gris perle",   hex: "#c4beb6", family: "grey",       code: "RF-2005" },
    "etoupe":       { zh: "大象灰",   en: "Etoupe",       hex: "#6b5b4b", family: "grey",       code: "RF-2006" },
    "gold":         { zh: "金棕",     en: "Gold",         hex: "#c4a05a", family: "gold-brown", code: "RF-3001" },
    "cognac":       { zh: "干邑",     en: "Cognac",       hex: "#8e4e22", family: "gold-brown", code: "RF-3002" },
    "fauve":        { zh: "黄褐",     en: "Fauve",        hex: "#b87333", family: "gold-brown", code: "RF-3003" },
    "camel":        { zh: "驼",       en: "Camel",        hex: "#b08452", family: "gold-brown", code: "RF-3004" },
    "havane":       { zh: "哈瓦那",   en: "Havane",       hex: "#7a4a28", family: "gold-brown", code: "RF-3005" },
    "chestnut":     { zh: "栗",       en: "Chestnut",     hex: "#703a1e", family: "gold-brown", code: "RF-3006" },
    "honey":        { zh: "蜜",       en: "Miel",         hex: "#bc8638", family: "gold-brown", code: "RF-3007" },
    "kraft":        { zh: "牛皮纸",   en: "Kraft",        hex: "#c49a5c", family: "gold-brown", code: "RF-3008" },
    "tabac":        { zh: "烟草",     en: "Tabac",        hex: "#5c3a22", family: "gold-brown", code: "RF-3009" },
    "chataigne":    { zh: "栗色",     en: "Chataigne",    hex: "#6a4030", family: "gold-brown", code: "RF-3010" },
    "craie":        { zh: "粉笔白",   en: "Craie",        hex: "#efe6d6", family: "light",      code: "RF-4001" },
    "cream":        { zh: "奶油",     en: "Cream",        hex: "#eee4d2", family: "light",      code: "RF-4002" },
    "ivory":        { zh: "象牙",     en: "Ivory",        hex: "#eadec8", family: "light",      code: "RF-4003" },
    "sand":         { zh: "沙",       en: "Sand",         hex: "#c6ae84", family: "light",      code: "RF-4004" },
    "natural-veg":  { zh: "植鞣本色", en: "Natural veg",  hex: "#c6a674", family: "light",      code: "RF-4005" },
    "craie-warm":   { zh: "暖米",     en: "Craie warm",   hex: "#e8dcc8", family: "light",      code: "RF-4006" },
    "oxblood":      { zh: "牛血",     en: "Oxblood",      hex: "#5c1618", family: "red",        code: "RF-5001" },
    "wine":         { zh: "酒红",     en: "Wine",         hex: "#561a26", family: "red",        code: "RF-5002" },
    "carmin":       { zh: "胭脂",     en: "Carmin",       hex: "#8c1e2e", family: "red",        code: "RF-5003" },
    "rouge":        { zh: "正红",     en: "Rouge",        hex: "#9a1c24", family: "red",        code: "RF-5004" },
    "brick":        { zh: "砖红",     en: "Brick",        hex: "#8a2e24", family: "red",        code: "RF-5005" },
    "orange":       { zh: "橙",       en: "Orange",       hex: "#c45a20", family: "orange",     code: "RF-6001" },
    "terra":        { zh: "赤陶",     en: "Terra",        hex: "#a65030", family: "orange",     code: "RF-6002" },
    "potiron":      { zh: "南瓜",     en: "Potiron",      hex: "#d46a28", family: "orange",     code: "RF-6003" },
    "jaune":        { zh: "姜黄",     en: "Jaune",        hex: "#d4a428", family: "yellow",     code: "RF-7001" },
    "butter":       { zh: "黄油",     en: "Butter",       hex: "#e0c46a", family: "yellow",     code: "RF-7002" },
    "vert-cypress": { zh: "柏绿",     en: "Vert cypress", hex: "#3a4a32", family: "green",      code: "RF-8001" },
    "cactus":       { zh: "仙人掌",   en: "Cactus",       hex: "#4a5c38", family: "green",      code: "RF-8002" },
    "olive":        { zh: "橄榄",     en: "Olive",        hex: "#4c562e", family: "green",      code: "RF-8003" },
    "moss":         { zh: "苔",       en: "Moss",         hex: "#5a623a", family: "green",      code: "RF-8004" },
    "vert-fonce":   { zh: "墨绿",     en: "Vert fonce",   hex: "#1e2e24", family: "green",      code: "RF-8005" },
    "navy":         { zh: "藏青",     en: "Navy",         hex: "#1e2842", family: "blue",       code: "RF-9001" },
    "indigo":       { zh: "靛蓝",     en: "Indigo",       hex: "#2a3a5c", family: "blue",       code: "RF-9002" },
    "bleu-nuit":    { zh: "夜蓝",     en: "Bleu nuit",    hex: "#1a2438", family: "blue",       code: "RF-9003" },
    "petrol":       { zh: "石油蓝",   en: "Petrol",       hex: "#2c4048", family: "blue",       code: "RF-9004" },
    "jean":         { zh: "牛仔蓝",   en: "Jean",         hex: "#3a5070", family: "blue",       code: "RF-9005" },
    "rose":         { zh: "玫瑰",     en: "Rose",         hex: "#c48a8a", family: "pink",       code: "RF-1101" },
    "sakura":       { zh: "樱粉",     en: "Sakura",       hex: "#e8b8b8", family: "pink",       code: "RF-1102" },
    "bois-de-rose": { zh: "紫檀粉",   en: "Bois de rose", hex: "#8a4a52", family: "pink",       code: "RF-1103" },
    "anemone":      { zh: "银莲",     en: "Anemone",      hex: "#5c3a5c", family: "purple",     code: "RF-1201" },
    "raisin":       { zh: "葡萄紫",   en: "Raisin",       hex: "#4a2a40", family: "purple",     code: "RF-1202" }
  },
  hides: [
    {
      id: "rf-tg-01",
      name_zh: "墨黑 Togo",
      name_en: "Ink Togo",
      category: "togo",
      category_zh: "Togo纹",
      category_en: "Togo",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-pebble",
      tannage_zh: "铬鞣卵石粒",
      tannage_en: "Chrome, pebble grain",
      thickness_mm: 1.6,
      width_cm: 135,
      price_cny_per_sqft: 118,
      price_usd_per_sqft: 16.5,
      colors: ["black", "gold", "etoupe", "cognac", "craie", "navy"],
      finish_zh: "大卵石粒，身骨挺，耐刮",
      finish_en: "Large pebble, firm body, scratch-tough",
      best_for_zh: "托特、通勤包",
      best_for_en: "Totes, everyday bags"
    },
    {
      id: "rf-tg-02",
      name_zh: "干邑 Togo",
      name_en: "Cognac Togo",
      category: "togo",
      category_zh: "Togo纹",
      category_en: "Togo",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-pebble",
      tannage_zh: "铬鞣卵石粒",
      tannage_en: "Chrome, pebble grain",
      thickness_mm: 1.8,
      width_cm: 132,
      price_cny_per_sqft: 128,
      price_usd_per_sqft: 18,
      colors: ["cognac", "gold", "etoupe", "chestnut", "craie", "navy"],
      finish_zh: "暖色大粒，挺，适合包",
      finish_en: "Warm large pebble, firm — bags",
      best_for_zh: "手袋、公文",
      best_for_en: "Handbags, briefs"
    },
    {
      id: "rf-tg-03",
      name_zh: "酒红 Togo",
      name_en: "Wine Togo",
      category: "togo",
      category_zh: "Togo纹",
      category_en: "Togo",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-pebble",
      tannage_zh: "铬鞣卵石粒",
      tannage_en: "Chrome, pebble grain",
      thickness_mm: 1.4,
      width_cm: 130,
      price_cny_per_sqft: 138,
      price_usd_per_sqft: 19.5,
      colors: ["wine", "oxblood", "black", "gold", "etoupe", "navy"],
      finish_zh: "薄一些仍挺，粒面清楚",
      finish_en: "Thinner, still firm, grain reads",
      best_for_zh: "手袋、卡套",
      best_for_en: "Handbags, card cases"
    },
    {
      id: "rf-sw-01",
      name_zh: "蜜色 Swift",
      name_en: "Honey Swift",
      category: "swift",
      category_zh: "Swift纹",
      category_en: "Swift",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-fine",
      tannage_zh: "铬鞣细软面",
      tannage_en: "Chrome, fine soft face",
      thickness_mm: 1.1,
      width_cm: 128,
      price_cny_per_sqft: 128,
      price_usd_per_sqft: 18,
      colors: ["honey", "gold", "cognac", "etoupe", "craie", "navy"],
      finish_zh: "极细软面，手感近光面",
      finish_en: "Very fine soft face, almost smooth",
      best_for_zh: "短夹、卡套",
      best_for_en: "Wallets, card cases"
    },
    {
      id: "rf-sw-02",
      name_zh: "象牙 Swift",
      name_en: "Ivory Swift",
      category: "swift",
      category_zh: "Swift纹",
      category_en: "Swift",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-fine",
      tannage_zh: "铬鞣细软面",
      tannage_en: "Chrome, fine soft face",
      thickness_mm: 0.9,
      width_cm: 126,
      price_cny_per_sqft: 148,
      price_usd_per_sqft: 21,
      colors: ["ivory", "craie", "cream", "gold", "etoupe", "navy"],
      finish_zh: "浅细软面，适合小皮件",
      finish_en: "Light fine face — small leather",
      best_for_zh: "小皮件、春夏袋",
      best_for_en: "Small leather, warm-weather bags"
    },
    {
      id: "rf-sw-03",
      name_zh: "藏青 Swift",
      name_en: "Navy Swift",
      category: "swift",
      category_zh: "Swift纹",
      category_en: "Swift",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-fine",
      tannage_zh: "铬鞣细软面",
      tannage_en: "Chrome, fine soft face",
      thickness_mm: 1.2,
      width_cm: 130,
      price_cny_per_sqft: 138,
      price_usd_per_sqft: 19.5,
      colors: ["navy", "black", "gold", "etoupe", "cognac", "craie"],
      finish_zh: "深色细软面，车线清楚",
      finish_en: "Dark fine face, stitching reads",
      best_for_zh: "长夹、钥匙包",
      best_for_en: "Long wallets, key holders"
    },
    {
      id: "rf-ep-01",
      name_zh: "黑色 Epsom",
      name_en: "Black Epsom",
      category: "epsom",
      category_zh: "Epsom纹",
      category_en: "Epsom",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-press",
      tannage_zh: "铬鞣规则压纹",
      tannage_en: "Chrome, regular press grain",
      thickness_mm: 1.3,
      width_cm: 138,
      price_cny_per_sqft: 108,
      price_usd_per_sqft: 15,
      colors: ["black", "gold", "etoupe", "cognac", "craie", "navy"],
      finish_zh: "规则压纹，硬挺好打理",
      finish_en: "Regular press, firm, easy care",
      best_for_zh: "结构包、电脑套",
      best_for_en: "Structured bags, laptop sleeves"
    },
    {
      id: "rf-ep-02",
      name_zh: "赤陶 Epsom",
      name_en: "Terra Epsom",
      category: "epsom",
      category_zh: "Epsom纹",
      category_en: "Epsom",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-press",
      tannage_zh: "铬鞣规则压纹",
      tannage_en: "Chrome, regular press grain",
      thickness_mm: 1.5,
      width_cm: 136,
      price_cny_per_sqft: 118,
      price_usd_per_sqft: 16.5,
      colors: ["terra", "gold", "cognac", "etoupe", "craie", "navy"],
      finish_zh: "暖色压纹，身骨硬",
      finish_en: "Warm press grain, hard body",
      best_for_zh: "公文、托特",
      best_for_en: "Briefs, totes"
    },
    {
      id: "rf-ep-03",
      name_zh: "炭灰 Epsom",
      name_en: "Charcoal Epsom",
      category: "epsom",
      category_zh: "Epsom纹",
      category_en: "Epsom",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-press",
      tannage_zh: "铬鞣规则压纹",
      tannage_en: "Chrome, regular press grain",
      thickness_mm: 1.1,
      width_cm: 134,
      price_cny_per_sqft: 128,
      price_usd_per_sqft: 18,
      colors: ["charcoal", "ash", "black", "etoupe", "gold", "navy"],
      finish_zh: "薄压纹，仍挺、好擦",
      finish_en: "Thinner press — still firm, wipes clean",
      best_for_zh: "卡套、手拿",
      best_for_en: "Card cases, clutches"
    },
    {
      id: "rf-cl-01",
      name_zh: "栗壳掌纹",
      name_en: "Chestnut palm",
      category: "clemence",
      category_zh: "掌纹",
      category_en: "Palm grain",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-palm",
      tannage_zh: "铬鞣掌纹",
      tannage_en: "Chrome, palm grain",
      thickness_mm: 1.8,
      width_cm: 132,
      price_cny_per_sqft: 108,
      price_usd_per_sqft: 15,
      colors: ["chestnut", "cognac", "gold", "etoupe", "craie", "navy"],
      finish_zh: "大掌纹，松软会塌",
      finish_en: "Large palm grain, slack and soft",
      best_for_zh: "软包、水桶",
      best_for_en: "Soft bags, buckets"
    },
    {
      id: "rf-cl-02",
      name_zh: "沙色掌纹",
      name_en: "Sand palm",
      category: "clemence",
      category_zh: "掌纹",
      category_en: "Palm grain",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-palm",
      tannage_zh: "铬鞣掌纹",
      tannage_en: "Chrome, palm grain",
      thickness_mm: 1.6,
      width_cm: 130,
      price_cny_per_sqft: 118,
      price_usd_per_sqft: 16.5,
      colors: ["sand", "craie", "natural-veg", "gold", "etoupe", "cognac"],
      finish_zh: "浅掌纹，松，慎防沾色",
      finish_en: "Light palm, slack — mark-prone",
      best_for_zh: "软托特、旅行袋",
      best_for_en: "Soft totes, duffels"
    },
    {
      id: "rf-tb-01",
      name_zh: "橄榄摔纹",
      name_en: "Olive tumbled",
      category: "tumbled",
      category_zh: "摔纹",
      category_en: "Tumbled",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-tumble",
      tannage_zh: "铬鞣摔纹",
      tannage_en: "Chrome, tumbled",
      thickness_mm: 1.6,
      width_cm: 128,
      price_cny_per_sqft: 98,
      price_usd_per_sqft: 14,
      colors: ["olive", "moss", "gold", "etoupe", "cognac", "navy"],
      finish_zh: "自然摔皱，不求平整",
      finish_en: "Natural tumbled creases, not flat",
      best_for_zh: "邮差包、休闲袋",
      best_for_en: "Messenger bags, casual totes"
    },
    {
      id: "rf-tb-02",
      name_zh: "深棕摔纹",
      name_en: "Deep brown tumbled",
      category: "tumbled",
      category_zh: "摔纹",
      category_en: "Tumbled",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-tumble",
      tannage_zh: "铬鞣摔纹",
      tannage_en: "Chrome, tumbled",
      thickness_mm: 1.8,
      width_cm: 130,
      price_cny_per_sqft: 108,
      price_usd_per_sqft: 15,
      colors: ["deep-brown", "black", "gold", "etoupe", "cognac", "navy"],
      finish_zh: "深色摔皱，用后更熟",
      finish_en: "Dark tumbled — breaks in with use",
      best_for_zh: "旅行袋、相机包",
      best_for_en: "Duffels, camera bags"
    },
    {
      id: "rf-ly-01",
      name_zh: "驼棕小纹",
      name_en: "Camel fine pebble",
      category: "lychee",
      category_zh: "小纹",
      category_en: "Fine pebble",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-lychee",
      tannage_zh: "铬鞣细荔枝",
      tannage_en: "Chrome, fine pebble",
      thickness_mm: 1.4,
      width_cm: 140,
      price_cny_per_sqft: 92,
      price_usd_per_sqft: 13,
      colors: ["camel", "gold", "cognac", "etoupe", "craie", "navy"],
      finish_zh: "细荔枝小纹，日常好打理",
      finish_en: "Fine lychee pebble, easy daily care",
      best_for_zh: "通勤包、钱包",
      best_for_en: "Everyday bags, wallets"
    },
    {
      id: "rf-ly-02",
      name_zh: "牛血红小纹",
      name_en: "Oxblood fine pebble",
      category: "lychee",
      category_zh: "小纹",
      category_en: "Fine pebble",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-lychee",
      tannage_zh: "铬鞣细荔枝",
      tannage_en: "Chrome, fine pebble",
      thickness_mm: 1.3,
      width_cm: 138,
      price_cny_per_sqft: 98,
      price_usd_per_sqft: 14,
      colors: ["oxblood", "wine", "black", "gold", "etoupe", "navy"],
      finish_zh: "细小纹，色相对稳",
      finish_en: "Fine pebble, steadier color",
      best_for_zh: "手袋、皮带",
      best_for_en: "Handbags, belts"
    },
    {
      id: "rf-bx-01",
      name_zh: "墨黑盒纹",
      name_en: "Ink box calf",
      category: "box",
      category_zh: "光面盒纹",
      category_en: "Box calf",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-tight",
      tannage_zh: "铬鞣紧面",
      tannage_en: "Chrome, tight grain",
      thickness_mm: 1.6,
      width_cm: 132,
      price_cny_per_sqft: 108,
      price_usd_per_sqft: 15,
      colors: ["black", "gold", "etoupe", "cognac", "craie", "navy"],
      finish_zh: "光面挺括，折痕干净",
      finish_en: "Smooth and firm, clean crease",
      best_for_zh: "包袋、小皮件",
      best_for_en: "Bags, small leather goods"
    },
    {
      id: "rf-bx-02",
      name_zh: "干邑盒纹",
      name_en: "Cognac box calf",
      category: "box",
      category_zh: "光面盒纹",
      category_en: "Box calf",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-tight",
      tannage_zh: "铬鞣紧面",
      tannage_en: "Chrome, tight grain",
      thickness_mm: 1.8,
      width_cm: 130,
      price_cny_per_sqft: 118,
      price_usd_per_sqft: 16.5,
      colors: ["cognac", "gold", "etoupe", "chestnut", "craie", "navy"],
      finish_zh: "光面偏暖，身骨偏硬",
      finish_en: "Warm face, firmer body",
      best_for_zh: "公文、皮带、托特",
      best_for_en: "Briefs, belts, totes"
    },
    {
      id: "rf-ll-01",
      name_zh: "酒红大纹",
      name_en: "Wine large pebble",
      category: "lychee-large",
      category_zh: "大纹",
      category_en: "Large pebble",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-lychee-large",
      tannage_zh: "铬鞣大荔枝",
      tannage_en: "Chrome, large pebble",
      thickness_mm: 1.5,
      width_cm: 136,
      price_cny_per_sqft: 96,
      price_usd_per_sqft: 13.5,
      colors: ["wine", "gold", "etoupe", "cognac", "black", "navy"],
      finish_zh: "大荔枝纹，粒比小纹疏",
      finish_en: "Large lychee — looser than fine pebble",
      best_for_zh: "托特、邮差包",
      best_for_en: "Totes, messenger bags"
    },
    {
      id: "rf-ll-02",
      name_zh: "苔绿大纹",
      name_en: "Moss large pebble",
      category: "lychee-large",
      category_zh: "大纹",
      category_en: "Large pebble",
      animal: "calf",
      animal_zh: "小牛",
      animal_en: "Calf",
      tannage: "chrome-lychee-large",
      tannage_zh: "铬鞣大荔枝",
      tannage_en: "Chrome, large pebble",
      thickness_mm: 1.4,
      width_cm: 134,
      price_cny_per_sqft: 92,
      price_usd_per_sqft: 13,
      colors: ["moss", "olive", "gold", "etoupe", "cognac", "navy"],
      finish_zh: "大纹清楚，日常耐用",
      finish_en: "Large pebble reads clearly, daily-tough",
      best_for_zh: "休闲袋、靴筒",
      best_for_en: "Casual bags, boot shafts"
    }
  ]
};
